from langchain_openai import ChatOpenAI
from langchain_pinecone import PineconeVectorStore
from dotenv import load_dotenv
import os
from langchain_openai import OpenAIEmbeddings
from app.models.image_response import Items

load_dotenv()
embedder = OpenAIEmbeddings(model="text-embedding-ada-002")

vision_model = ChatOpenAI(model="gpt-4o", temperature=0)

index_name = os.getenv("PINECONE_INDEX_NAME")

docsearch = PineconeVectorStore.from_existing_index(
    index_name=index_name, embedding=embedder
)

# max marginal search to encourage document diversity when retrieving (but slows down retrieval process)
# retriever = docsearch.as_retriever(
#     search_type="mmr", search_kwargs={"k": 6, "fetch_k": 10}
# )
retriever = docsearch.as_retriever()

qa_model = ChatOpenAI(model="gpt-3.5-turbo", temperature=0)

qa_model_item_names_output = qa_model.with_structured_output(Items, method="json_mode")


NEA_ITEM_NAMES = [
    "9-Volt battery",
    "Aerosol cans",
    "Air Conditioner",
    "Alkaline battery",
    "Ang pow",
    "Anniversary card",
    "Assessment books",
    "Atm card",
    "Audio sound system",
    "Bag",
    "Bakeware",
    "Baking paper",
    "Bank card",
    "Basketball",
    "Battery charger",
    "Bed frame",
    "Bedsheet",
    "Beer can",
    "Beverage carton",
    "Beverage glass bottle",
    "Beverage metal can",
    "Bill",
    "Bio-degradable bag",
    "Birthday card",
    "Biscuit tin",
    "Biscuits",
    "Blanket",
    "Blister pack",
    "Blouse",
    "Bodywash bottle",
    "Books",
    "Boots",
    "Borosilicate glassware",
    "Briefcase",
    "Brochure (Glossy and non-glossy)",
    "Bubble tea cups",
    "Bubble wrap",
    "Bulky waste",
    "Business card",
    "Button cell battery",
    "CD",
    "CD casing",
    "CD player",
    "Cabinet",
    "Calendar",
    "Camisole",
    "Candy",
    "Canned food",
    "Carbonated drink bottle",
    "Carbonated drink can",
    "Cardboard box",
    "Carton box",
    "Cassette",
    "Cellphone",
    "Ceramic plate",
    "Ceramic products",
    "Cereal box",
    "Chair",
    "Chairs",
    "Child seat",
    "Chilli sauce bottle",
    "Chocolate",
    "Christmas card",
    "Cigarettes",
    "Clean aluminium foil",
    "Clean aluminium tray",
    "Cling film",
    "Clothes",
    "Coffee capsules",
    "Coffee table",
    "Comic books",
    "Compact disc",
    "Computer battery",
    "Computer mouse",
    "Containers",
    "Cookies",
    "Cooking pot",
    "Correction liquid",
    "Correction tape",
    "Cosmetic glass bottle",
    "Cotton bud",
    "Cotton wool",
    "Couch",
    "Crackers",
    "Crayon drawing",
    "Crocs",
    "Crystal glass",
    "Cupboard",
    "Curtains",
    "Cushion",
    "DVD",
    "DVD casing",
    "DVD player",
    "Debit card",
    "Desktop computer",
    "Desktop monitor",
    "Detergent bottle",
    "Diaper",
    "Diary",
    "Dining table",
    "Dirty aluminium foil",
    "Dirty aluminium tray",
    "Disposable bowl",
    "Disposable cup",
    "Disposable cutlery",
    "Disposable fork",
    "Disposable knife",
    "Disposable plate",
    "Disposable shaver",
    "Disposable spoon",
    "Disposable wooden chopsticks",
    "Docking station",
    "Dress shoes",
    "Drink packet",
    "Drinking glass",
    "Drinking straw",
    "Drumstick",
    "Dryer",
    "E-scooter",
    "Electric bicycle",
    "Electric fan",
    "Electric kettle",
    "Electric mobility devices",
    "Electric mobility scooter",
    "Electric scooter",
    "Electric shaver",
    "Electronic cables",
    "Electronic waste",
    "Envelope (With and without plastic window)",
    "Eraser",
    "Exam papers",
    "Exercise book",
    "Expired credit cards",
    "Fabric",
    "Facial cleanser bottle",
    "Fan",
    "Fire wire",
    "Fish",
    "Fluorescent bulb",
    "Fluorescent lamp",
    "Flyer (Glossy and non-glossy)",
    "Food blender",
    "Food glass bottle",
    "Food jars",
    "Food metal can",
    "Food peels",
    "Food processor",
    "Food tin",
    "Food waste",
    "Foolscap paper",
    "Football",
    "Football shoes (without metal studs)",
    "Fridge",
    "Fruit box",
    "Furniture",
    "Gaming console",
    "Gift",
    "Gift bag",
    "Gift wrapping paper",
    "Gifts",
    "Glad wrap",
    "Glass Bakeware",
    "Glass Beer bottle",
    "Glass Tube",
    "Glass Wine bottle",
    "Glass bottle",
    "Glass condiment bottle",
    "Glass cup",
    "Glass plate",
    "Glass sauce bottle",
    "Glass with metal wires",
    "Glasses",
    "Glassware",
    "Glitter paper",
    "Golf ball",
    "Graph paper",
    "Green packet",
    "Greeting card",
    "Gummy bears",
    "Handphone",
    "Hard disk drive",
    "Heels",
    "Highlighter",
    "Hong bao",
    "Horticultural waste",
    "Household battery",
    "Incandescent bulb",
    "Incandescent lamp",
    "Iron",
    "Ironing board",
    "Jacket",
    "Jam spread bottle",
    "Joss sticks",
    "Jotter book",
    "Journal",
    "Juice packet",
    "Ketchup bottle",
    "Keyboard",
    "Kitchen roll",
    "Kitchen towel",
    "LED bulb",
    "LED lamp",
    "Lamp",
    "Lamp fixture",
    "Lamp stand",
    "Laptop",
    "Large household appliances",
    "Leaflet",
    "Leftover medicine",
    "Leftovers",
    "Letter",
    "Light bulb",
    "Liquor bottle",
    "Luggage bag",
    "Magazine (Glossy and non-glossy)",
    "Mail",
    "Make up",
    "Marker",
    "Masks",
    "Mason jar",
    "Mattress",
    "Meat",
    "Medals",
    "Medicine glass bottle",
    "Medicine pack",
    "Melamine cups",
    "Melamine plates",
    "Melamine products",
    "Metal accessories",
    "Metal bottle cap",
    "Metal container",
    "Metal cutlery",
    "Metal paint cans",
    "Metal paint container",
    "Microwave oven",
    "Milk carton",
    "Mineral water bottle",
    "Mirror",
    "Mobile phone",
    "Mobile phone battery",
    "Modem",
    "Mouth wash",
    "Mouthwash bottle",
    "Music player",
    "Namecard",
    "Newsletter",
    "Newspaper",
    "Nintendo",
    "Non-food metal container",
    "Noodles",
    "Notebook",
    "Notes",
    "Notice",
    "Novel",
    "Oven-safe food containers",
    "Oxo-degradable bag",
    "Packaging",
    "Pampers",
    "Pamphlet",
    "Pants",
    "Paper",
    "Paper Packaging (printed paper box etc)",
    "Paper bag",
    "Paper box",
    "Paper cup",
    "Paper disposables",
    "Paper egg trays",
    "Paper packaging contaminated with food",
    "Paper packaging with food",
    "Paper plate",
    "Paper receipt",
    "Paper towel",
    "Paper towel tube",
    "Parchment paper",
    "Pen",
    "Pencil",
    "Perfume glass bottle",
    "Permanent marker",
    "Personal mobility devices",
    "Pizza",
    "Pizza boxes",
    "Plant waste",
    "Plaster",
    "Plastic Bread bag",
    "Plastic Water bottle",
    "Plastic bag",
    "Plastic bottle",
    "Plastic bottle cap",
    "Plastic bowl",
    "Plastic bubble tea carrier",
    "Plastic carbonated drink bottle",
    "Plastic clothes hanger",
    "Plastic container",
    "Plastic crockery",
    "Plastic cup lids",
    "Plastic cups",
    "Plastic cutlery",
    "Plastic disposables",
    "Plastic egg trays",
    "Plastic envelope",
    "Plastic film",
    "Plastic food wrap",
    "Plastic fork",
    "Plastic fruit box",
    "Plastic fruit container",
    "Plastic knife",
    "Plastic magazine wrapper",
    "Plastic medicine bottle",
    "Plastic milk bottles",
    "Plastic packaging",
    "Plastic packaging contaminated with food/oil stains",
    "Plastic packaging for packet drink",
    "Plastic packaging with foil",
    "Plastic pill bottle",
    "Plastic plate",
    "Plastic saucer",
    "Plastic serving bowl",
    "Plastic serving plate",
    "Plastic soft drink bottle",
    "Plastic spoon",
    "Plastic spork",
    "Plastic takeaway food container",
    "Playstation",
    "Polystyrene foam product",
    "Porcelain",
    "Portable charger",
    "Post-it",
    "Potato chip bags",
    "Power bank",
    "Power-assisted bicycle",
    "Present",
    "Presents",
    "Printed paper (Glossy and non-glossy)",
    "Printed paper box",
    "Printer",
    "Publication",
    "Pumps",
    "Pyrex glassware",
    "Radio",
    "Rechargeable battery",
    "Red packet",
    "Red wine bottle",
    "Refrigerator",
    "Ribbons",
    "Rice",
    "Rice cooker",
    "Robot cleaner",
    "Robot vacuum",
    "Roller blades",
    "Roller skates",
    "Rotten food",
    "Router",
    "Ruler",
    "Rusty metal cans",
    "Sandles",
    "Sanitary pad",
    "Saran wrap",
    "Sauce bottle",
    "School shoes",
    "Seafood",
    "Seal bag",
    "Shampoo",
    "Shampoo bottle",
    "Shirts",
    "Shoe rack",
    "Shoes",
    "Shorts",
    "Shot glass",
    "Shredded paper",
    "Singlet",
    "Skirt",
    "Sneakers",
    "Soap bottle",
    "Soda cans",
    "Sofa",
    "Soft drink bottle",
    "Soft drink can",
    "Speaker",
    "Spectacles",
    "Spoiled food",
    "Sports shoes",
    "Spray cans",
    "Stamps",
    "Standing fan",
    "Stationery",
    "Steel wool",
    "Stool",
    "Storybook",
    "Styrofoam",
    "Styrofoam clamshell container",
    "Styrofoam cup",
    "Supplement glass bottle",
    "Sweets",
    "Switch",
    "T-shirt",
    "TV",
    "Table",
    "Tablet computer",
    "Takeaway",
    "Tea pot",
    "Telephone directory",
    "Television",
    "Tempered glass",
    "Tennis ball",
    "Textbooks",
    "Textile",
    "Tie",
    "Tissue box",
    "Tissue box packaging",
    "Tissue paper",
    "Toaster oven",
    "Toilet paper",
    "Toilet paper packaging",
    "Toilet roll tube",
    "Toys",
    "Tupperware plastic container",
    "Umbrella",
    "Vacuum cleaner",
    "Vase",
    "Vegetables",
    "Video tape",
    "Washing machine",
    "Wax paper",
    "Wet wipes",
    "White wine bottle",
    "Whiteboard marker",
    "Whskey glass",
    "Wii",
    "Windows",
    "Wine bottle",
    "Wine glass",
    "Wooden chopsticks",
    "Wrapper",
    "Writing paper",
    "Ziplock bag",
]
