from langchain_core.prompts import ChatPromptTemplate

NEA_ITEM_NAMES = [
    "9-Volt battery",
    "Aerosol cans",
    "Air Conditioner",
    "Alkaline battery",
    "Audio sound system",
    "Bag",
    "Bakeware",
    "Battery charger",
    "Bedsheet",
    "Beer bottle",
    "Beer can",
    "Beverage carton",
    "Beverage glass bottle",
    "Beverage metal can",
    "Bio-degradable bag",
    "Biscuit tin",
    "Blanket",
    "Blister pack",
    "Bodywash bottle",
    "Books",
    "Borosilicate glassware",
    "Bread bag",
    "Briefcase",
    "Brochure (Glossy and non-glossy)",
    "Bubble tea cups",
    "Bubble wrap",
    "Bulky waste",
    "Button cell battery",
    "CD",
    "CD casing",
    "CD player",
    "Calendar",
    "Canned food",
    "Carbonated drink bottle",
    "Carbonated drink can",
    "Cardboard box",
    "Carton box",
    "Cassette",
    "Ceramic plate",
    "Ceramic products",
    "Chairs",
    "Child seat",
    "Cigarettes",
    "Clean aluminium foil",
    "Clean aluminium tray",
    "Cling film",
    "Clothes",
    "Coffee capsules",
    "Computer battery",
    "Computer mouse",
    "Condiment bottle",
    "Cooking pot",
    "Cosmetic glass bottle",
    "Cotton bud",
    "Cotton wool",
    "Crayon drawing",
    "Crystal glass",
    "Curtains",
    "DVD",
    "DVD casing",
    "DVD player",
    "Desktop computer",
    "Desktop monitor",
    "Detergent bottle",
    "Diaper",
    "Dirty aluminium foil",
    "Dirty aluminium tray",
    "Disposable shaver",
    "Disposable wooden chopsticks",
    "Docking station",
    "Drink packet",
    "Drinking glass",
    "Drinking straw",
    "Dryer",
    "E-scooter",
    "Electric bicycle",
    "Electric fan",
    "Electric kettle",
    "Electric mobility devices",
    "Electric mobility scooter",
    "Electric scooter",
    "Electric shaver",
    "Electronic cables",
    "Electronic waste",
    "Envelope (With and without plastic window)",
    "Expired credit cards",
    "Facial cleanser bottle",
    "Fluorescent bulb",
    "Fluorescent lamp",
    "Flyer (Glossy and non-glossy)",
    "Food blender",
    "Food glass bottle",
    "Food jars",
    "Food metal can",
    "Food processor",
    "Food tin",
    "Food waste",
    "Football shoes (without metal studs)",
    "Fridge",
    "Fruit box",
    "Furniture",
    "Gaming console",
    "Gift wrapping paper",
    "Glad wrap",
    "Glass bottle",
    "Glass cup",
    "Glass plate",
    "Glass with metal wires",
    "Glassware",
    "Glitter paper",
    "Greeting card",
    "Hard disk drive",
    "Horticultural waste",
    "Household battery",
    "Incandescent bulb",
    "Incandescent lamp",
    "Jam spread bottle",
    "Joss sticks",
    "Juice packet",
    "Keyboard",
    "LED bulb",
    "LED lamp",
    "Lamp",
    "Lamp fixture",
    "Lamp stand",
    "Laptop",
    "Large household appliances",
    "Leftover medicine",
    "Light bulb",
    "Liquor bottle",
    "Luggage bag",
    "Magazine (Glossy and non-glossy)",
    "Magazine wrapper",
    "Masks",
    "Medals",
    "Medicine bottle",
    "Medicine glass bottle",
    "Melamine cups",
    "Melamine plates",
    "Melamine products",
    "Metal accessories",
    "Metal bottle cap",
    "Metal container",
    "Metal cutlery",
    "Microwave oven",
    "Milk bottles",
    "Milk carton",
    "Mineral water bottle",
    "Mirror",
    "Mobile phone",
    "Mobile phone battery",
    "Modem",
    "Mouthwash bottle",
    "Music player",
    "Namecard",
    "Newsletter",
    "Newspaper",
    "Non-food metal container",
    "Oven-safe food containers",
    "Oxo-degradable bag",
    "Paint cans",
    "Paint container",
    "Paper",
    "Paper Packaging (printed paper box etc)",
    "Paper bag",
    "Paper box",
    "Paper cup",
    "Paper disposables",
    "Paper egg trays",
    "Paper packaging contaminated with food",
    "Paper packaging with food",
    "Paper plate",
    "Paper receipt",
    "Paper towel",
    "Paper towel tube",
    "Pen",
    "Pencil",
    "Perfume glass bottle",
    "Personal mobility devices",
    "Pizza boxes",
    "Plant waste",
    "Plastic bag",
    "Plastic bottle",
    "Plastic bottle cap",
    "Plastic clothes hanger",
    "Plastic container",
    "Plastic crockery",
    "Plastic cups",
    "Plastic cutlery",
    "Plastic disposables",
    "Plastic egg trays",
    "Plastic envelope",
    "Plastic film",
    "Plastic food wrap",
    "Plastic packaging",
    "Plastic packaging contaminated with food/oil stains",
    "Plastic packaging for packet drink",
    "Plastic packaging with foil",
    "Plastic takeaway food container",
    "Polystyrene foam product",
    "Porcelain",
    "Portable charger",
    "Potato chip bags",
    "Power bank",
    "Power-assisted bicycle",
    "Printed paper (Glossy and non-glossy)",
    "Printed paper box",
    "Printer",
    "Pyrex glassware",
    "Radio",
    "Rechargeable battery",
    "Red packet",
    "Refrigerator",
    "Ribbons",
    "Rice cooker",
    "Router",
    "Rusty metal cans",
    "Sanitary pad",
    "Saran wrap",
    "Sauce bottle",
    "School shoes",
    "Shampoo",
    "Shampoo bottle",
    "Shoes",
    "Shredded paper",
    "Soap bottle",
    "Soft drink bottle",
    "Soft drink can",
    "Speaker",
    "Spectacles",
    "Sports shoes",
    "Spray cans",
    "Standing fan",
    "Stationery",
    "Steel wool",
    "Styrofoam",
    "Styrofoam clamshell container",
    "Styrofoam cup",
    "Supplement glass bottle",
    "TV",
    "Table",
    "Tablet computer",
    "Tea pot",
    "Telephone directory",
    "Television",
    "Tempered glass",
    "Textbooks",
    "Textile",
    "Tissue box",
    "Tissue box packaging",
    "Tissue paper",
    "Toaster oven",
    "Toilet paper",
    "Toilet paper packaging",
    "Toilet roll tube",
    "Toys",
    "Tube",
    "Umbrella",
    "Vacuum cleaner",
    "Vase",
    "Video tape",
    "Washing machine",
    "Water bottle",
    "Wax paper",
    "Wet wipes",
    "Windows",
    "Wine bottle",
    "Wine glass",
    "Wooden chopsticks",
    "Writing paper",
    "Ziplock bag",
]


SYSTEM_MESSAGE = "You are an expert on answering questions briefly and accurately about recycling in Singapore. Your name is Bloo. Users may send you images of items to check if the items can be recycled, and your task is to correctly identify what are the items in the image, and eventually answer the users questions in a helpful, correct and concise manner."
